name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'simple_live_app/android/**'
      - 'simple_live_app/lib/**'
      - 'simple_live_app/pubspec.yaml'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true 

      # --- 关键修复：同时创建虚拟的属性文件和虚拟的密钥库文件 ---
      - name: Create Dummy Signing Files
        run: |
          # 1. 创建一个空的 dummy.jks 文件来满足文件存在性检查
          # 注意路径是 android/app/dummy.jks
          touch simple_live_app/android/app/dummy.jks

          # 2. 创建 key.properties 文件，指向我们刚刚创建的空文件
          echo "storeFile=dummy.jks" > simple_live_app/android/key.properties
          echo "storePassword=dummy" >> simple_live_app/android/key.properties
          echo "keyPassword=dummy" >> simple_live_app/android/key.properties
          echo "keyAlias=dummy" >> simple_live_app/android/key.properties
          
      - name: Restore and Upgrade Packages
        run: |
          cd simple_live_app
          flutter pub upgrade
      
      - name: Build Android APK (Debug)
        run: |
          cd simple_live_app
          flutter build apk --debug --split-per-abi

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-debug.apk```

### 这次修改的要点：

1.  **步骤名称更新**：我将步骤名从 `Create Dummy Key Properties` 改为了 `Create Dummy Signing Files`，更准确地描述了它的工作。
2.  **创建空文件**：在写 `key.properties` 之前，我们先用 `touch simple_live_app/android/app/dummy.jks` 命令，在 Gradle 会去检查的路径下，创建了一个0kb的空文件。
3.  **满足所有检查**：这样一来，Gradle 的签名检查无论是检查 `key.properties` 的内容，还是检查 `dummy.jks` 文件的物理存在，都会得到满足，从而顺利地放行，让 `debug` 构建继续进行。

请您提交这个修改。这次我们为那个“固执的门卫”提供了一整套的“假证件”，它没有理由再把我们拦在门外了。
