name: Build Windows Release

# 当你创建一个以 "v" 开头的 Git 标签 (e.g., v1.0.0) 并推送到GitHub时，此工作流会自动触发
on:
  push:
    tags:
      - "v*"
  # 也允许你手动触发
  workflow_dispatch:

jobs:
  # 任务：打包Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. 签出代码
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      # 2. 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          cache: true

      # 3. 开启Windows桌面支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      # 4. 获取依赖
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub upgrade

      # 5. 安装打包工具
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # 6. 打包Windows应用
      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets msix,zip --skip-clean

      # 7. 上传Windows包作为产物
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip
